### ISSUE TITLE
Constrained Target Space occasionally outputs the wrong parameters for a maximum

### ISSUE THREAD

**Issue by till-m** [bayesian-optimization/BayesianOptimization#428]
**Describe the bug**
If two points are registered with the same maximum target value, but the first one is disallowed and the second is not, then `.max()` outputs the disallowed one.

**To Reproduce**
A concise, self-contained code snippet that reproduces the bug you would like to report.
```python

import pytest
import numpy as np
from bayes_opt.constraint import ConstraintModel
from bayes_opt.target_space import TargetSpace
from bayes_opt.util import NotUniqueError


def target_func(**kwargs):
    # arbitrary target func
    return sum(kwargs.values())


PBOUNDS = {'p1': (0, 1), 'p2': (1, 100)}

def test_max_with_constraint():
    constraint = ConstraintModel(lambda p1, p2: p1-p2, -2, 2)
    space = TargetSpace(target_func, PBOUNDS, constraint=constraint)

    assert space.max() == None
    space.probe(params={"p1": 1, "p2": 2}) # Feasible
    space.probe(params={"p1": 0, "p2": 5}) # Unfeasible
    space.probe(params={"p1": 5, "p2": 8}) # Unfeasible
    space.probe(params={"p1": 2, "p2": 3}) # Feasible
    space.probe(params={"p1": 1, "p2": 6}) # Unfeasible
    assert space.max() == {"params": {"p1": 2, "p2": 3}, "target": 5, "constraint": -1}
```

**Additional context**
This seems to happen because [this line](https://github.com/bayesian-optimization/BayesianOptimization/blob/0d5105dcc25263b2911262dafcb61da28209ac8f/bayes_opt/target_space.py#L293) simply takes the first parameter combo with the matching target value, but does not check whether this is in fact the allowed one.
CC: @leandrobbraga

**Comment by leandrobbraga** [comment]
Can you assign this to me? Tomorrow I'll have a look at it
