### ISSUE TITLE
Give user access to in acq_max function

### ISSUE THREAD

**Issue by wending1** [bayesian-optimization/BayesianOptimization#431]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Some target function may be extremely expensive to sample, have a default and non-changeable n_warmup=10000 is unacceptable in some cases.

**Describe the solution you'd like**
Add a parameter n_warmup in general BayesianOptimization to control number of warm up points.

**References or alternative approaches**
If this feature was described in literature, please add references here. Additionally, feel free to add descriptions of any alternative solutions or features you've considered.

**Additional context**

**Are you able and willing to implement this feature yourself and open a pull request?**
- [ ] Yes, I can provide this feature.

**Comment by till-m** [comment]
`acq_max` samples from/maximize over the something making use of the GP approximation, not the target function.

**Comment by till-m** [comment]
Hey @wending1, is this still an issue for you?

**Comment by wending1** [comment]
This is not an issue any more, you can close it, thanks.
