### ISSUE TITLE
support multiple parameters

### ISSUE THREAD

**Issue by MarkMa1990** [bayesian-optimization/BayesianOptimization#442]
**Describe the solution you'd like**

imagine the input is an array containing 100 parameters, the bounds setup seems to be args of the black box function, it is insane to define the bounds one by one. Is there anyway to improve that?

**Are you able and willing to implement this feature yourself and open a pull request?**
- [ ] Yes, I can provide this feature.

**Comment by till-m** [comment]
See #349.

**Comment by MarkMa1990** [comment]
> See #349 (including the caveats mentioned for applying BO to such a high-dimensional problem).

Thank you, it works
