### ISSUE TITLE
Make n_restarts_optimizer dynamic

### ISSUE THREAD

**Issue by hwrightson** [bayesian-optimization/BayesianOptimization#448]
Just looking at an application of this in some custom code, and please let me know whether I'm correct in understanding that _n_restarts_optimizer_ in the [BayesianOptimisation function](https://github.com/bayesian-optimization/BayesianOptimization/blob/11a0c6aba1fcc6b5d2716052da5222a84259c5b9/examples/duplicate_point.py#L13) is the parameter that controls the number of runs/iterations the optimiser takes to reach a final output?

If so, my question is whether there is any reason why _n_restarts_optimizer_ is not parameterised?

Currently it's hard coded to 20 (our optimiser performs 20 iterations and I can see no other reference to this figure in my code, hence my logic at the top of this post), but I see no reason why we couldn't make this a default parameter value and allow users to specify their own number of iterations? Fairly simple fix I think and I'm happy to open a PR if anyone agrees?

**Comment by till-m** [comment]
Hi @hwrightson,

I think you might be confusing two things:
- `n_restarts_optimizer` refers to the number of times the GPR parameter maximum likelihood optimization is performed during the fitting process. This is a (meta-)parameter of the GP and can be set by calling `BayesianOptimization.set_gp_params`. See [here](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html) for more info.
- If you're looking for the parameter controlling the number of steps the bayesian optimizer performs, that is controlled through the `n_iter` parameter of the `BayesianOptimization.maximize` function.

Let me know if this helps.

**Comment by hwrightson** [comment]
Hi @till-m many thanks for the quick response! Much appreciated. 

Looks like I completely misconstrued what was going on in my pipeline, thank you for the pointers, I think I've got a better idea of what's going on now. I'll close the issue as you've answered my question 👍 

All the best, H
