### ISSUE TITLE
Pass *args, *kwargs as non-optimized arguments to the cost function

### ISSUE THREAD

**Issue by lindeloev** [bayesian-optimization/BayesianOptimization#451]
We have a cost function that uses some expensive-to-compute objects that remain constant across iterations. It would be nice to pass these to the cost function explicitly. Is this possible? If not, I think it would be a great feature in an already-awesome module!

Pseudocode of the enhanced API:

```python
def run_simulation(x, y, expensive_data):
    """A black box function. 
    Runs a simulation without having to compute `expensive_data` on each run."""
    simulation_result = run_simulation(expensive_data, x, y)
    return simulation_result.score()


def run_fold(df, fold):
    # Compute this once
    expensive_data = some_expensive_function(df, fold)

    # Now iterate over x and y, 
    # passing expensive_data to black_box_function on each iteration
    optimizer = BayesianOptimization(
        f=run_simulation,
        pbounds={'x': (2, 4), 'y': (-3, 3)},

        # I suggest adding this ability!
        **{"expensive_data": expensive_data}
    )
    optimizer.maximize()
    return optimizer.max

```

Currently, we enclose `run_simulation()` inside `run_fold()` so it statefully references `expensive_data ` from the higher namespace. This makes the code less clear and prone to bugs. Computing `expensive_data` within `run_simulation()` would be prohibitively expensive.

In our case, we optimize the parameters of a fairly-cheap simulation. We run the optimization for each of a number of cross-validation folds as sort of a nested hyperparameter tuning. There's some heavy computing involved in setting up the objects for each fold.

**Comment by till-m** [comment]
Hi @lindeloev,

if you're not opposed to handling things a bit more manually, maybe checkout Suggest-Evaluate-Register [here](https://github.com/bayesian-optimization/BayesianOptimization/blob/master/examples/advanced-tour.ipynb).

Would that suffice for your purpose?

**Comment by lindeloev** [comment]
Thanks, @till-m, that's good! For the record for future visitors, you can mix to-be-optimized-parameters and static-parameters like this:

```python
from bayes_opt import BayesianOptimization
from bayes_opt import UtilityFunction

def run_simulation(x, y, expensive_data):
    """A black box function. 
    Runs a simulation without having to compute `expensive_data` on each run."""
    simulation_result = run_simulation(expensive_data, x, y)
    return simulation_result.score()

def run_fold(df, fold):
    # Compute this once
    expensive_data = some_expensive_function(df, fold)

    # Set up optimizer
    utility = UtilityFunction()
    optimizer = BayesianOptimization(
        f=None,
        pbounds={'x': (2, 4), 'y': (-3, 3)}
    )

    # Now search iteratively
    for _ in range(100):
        next_point = optimizer.suggest(utility)
        target = run_simulation(**next_point, expensive_data = expensive_data)
        optimizer.register(params=next_point, target=target)
        
    return optimizer.max
```

Closing this issue. Feel free to re-open if you think it's worth supporting **kwargs in the default `BayesianOptimization()` usage.

**Comment by till-m** [comment]
Glad it worked for you!

Ideally I'd like to keep `.maximize()` simple and instead allow users to handle more complex cases themselves, individually, via suggest-evaluate-register or by using surrogate functions.
