### ISSUE TITLE
Verbose=2 doesn't work in terminal or bash

### ISSUE THREAD

**Issue by Dmonzer** [bayesian-optimization/BayesianOptimization#452]
Ex:
```python
from bayes_opt import BayesianOptimization

black_box_function = lambda x, y: -x ** 2 - (y - 1) ** 2 + 1

pbounds = {'x': (2, 4), 'y': (-3, 3)}

optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds, 
verbose =2
)
optimizer.maximize()
```

**Expected behavior**
I expect to get a printout of the progress outputs during the optimization process in power shell or git bash similar to jupyter notebook. 

**Environment (please complete the following information):**
 - OS: [Windows]

**Additional context**
When I run the same code in jupyter notebook, I get a log of optimization steps's output. However if I use powershell or git bash, I don't get any output.

**Comment by till-m** [comment]
Hey @Dmonzer,

thanks for reporting this issue. Unfortunately, I don't have a windows machine. Running on macOS in zsh, I do get a verbose output.

If you're willing to make a PR to fix this, that'd be great.
