### ISSUE TITLE
[Question] can I use ML model as a black_box function?

### ISSUE THREAD

**Issue by henjoe** [bayesian-optimization/BayesianOptimization#462]
Hi, black box function is a function that returns an output based on a mathematical model or equation, supposed I dont know the specific function or equation, is it possible to use a mahine learning model for this as a black box function to optimize? 
I just dont know if it is possible. 
Simply I have a

def myFunct(a,b,c): 
   Return myModel prediction based on a,b and c inputs.

and use myFunc as a blackbox function.

**Comment by EnthusiasticTeslim** [comment]
yes! something in the form:

```
def myFunct(input):
    output = model(input)
    return output
```

**Comment by henjoe** [comment]
Thanks! This is awesome! 

Regarss
