### ISSUE TITLE
How to use specific init_points

### ISSUE THREAD

**Issue by Forestsene** [bayesian-optimization/BayesianOptimization#464]
I want to use this program to find the max of black_box_function:
```
def black_box_function(x):
    return x**2
​
new_optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={"x": (-2, 2)},
    verbose=2,
    random_state=7,
)
​
new_optimizer.maximize(
    init_points=2,
    n_iter=1,
)
```

When I set "init_points=2"，this program will choose 2 point randomly. What should I do if I want to use 2 specific points, such as (0,0) and (1,1) ,instead of two random points. 

Thank you very much

**Comment by till-m** [comment]
Hey @Forestsene,

You can use `new_optimizer.probe(point, lazy=True)`.

Note that you need to call `probe` with individual points (i.e. not a list of points), so for 2 points you need to call it twice. The `lazy` parameter controls whether the point will be probed immediately or only when calling `maximize`. You should set `init_points=0` if you don't want additional randomly sampled points.

**Comment by Forestsene** [comment]
Thank you very much! I use specific init_points successfully:
```
new_optimizer.probe(0, lazy=True)
new_optimizer.probe(1, lazy=True)

new_optimizer.maximize(
    init_points=0,
    n_iter=1,
)
```
