### ISSUE TITLE
Experience with 4D or higher parameter spaces

### ISSUE THREAD

**Issue by BSchuett-fzi** [bayesian-optimization/BayesianOptimization#469]
I've been utilizing the BayesOpt library to optimize parameter spaces across different dimensions within my project. While the optimization process has been smooth for 2 and 3-dimensional spaces, I've encountered challenges when scaling up to 4 dimensions.

In 2D and 3D, the optimization proceeds as expected, eventually converging on the best parameter combinations. Although the computational time for 3D is slightly longer than for 2D, it's within reasonable bounds.

However, when transitioning to 4D spaces, I've noticed a deterioration in the optimization results. Despite increasing the iteration count, I've had to halt the process at 2000 iterations due to excessive calculation time.

Are there any specific considerations or adjustments necessary when working with higher dimensional spaces in the BayesOpt library. Are there certain parameters or settings that I should be mindful of for 4D optimization? Additionally, are there any potential oversights on my part that could be impacting the optimization process?

I also tried different 4D models,but the results are the same for all of them.
Please let me know if additional information is needed.

**Comment by till-m** [comment]
Hi @BSchuett-fzi,

I assume that your function is reasonably well conditioned and differentiable. If that's the case, 2000 iterations really should not happen.
One quick and easy thing to try: By default, this optimizer uses the `Matern` kernel with an isotropic lengthscale setting. If your problem is not isotropic, I could see this causing issues. You can use
```python
# instatiate the optimizer
...
# replace kernel
kernel = Matern(nu=2.5),
            alpha=1e-6,
            normalize_y=True,
            n_restarts_optimizer=5,
            length_scale=np.ones(4), # default = 1.0
            random_state=optimizer.random_state
)
optimizer.set_gp_params(kernel=kernel)
# optimization loop
...
```
to replace it with an isotropic one.

Let us know if this helps.

**Comment by BSchuett-fzi** [comment]
Thanks for your hint.
I'm sorry to ask, but do I still use a GaussianProcessRegressor? I have this code now:

```python 
gp = GaussianProcessRegressor(kernel = Matern(nu=2.5),
                            alpha=1e-6,
                            normalize_y=True,
                            n_restarts_optimizer=5,
                            length_scale=np.ones(4),  # default = 1.0
                            random_state=optimizer._random_state)
            optimizer.set_gp_params(kernel=gp)
```

But the length_scale is not an existing argument. I use scikit-learn  1.3.2.

**Comment by till-m** [comment]
Hi @BSchuett-fzi,

I will close this issue for now with the hope that the problem has been fixed. If it persits, feel free to reopen.
