### ISSUE TITLE
Inclusion of other adquisition functions

### ISSUE THREAD

**Issue by oarcelus** [bayesian-optimization/BayesianOptimization#475]
I was wondering if it would be possible to includo other adquistion functions in the library.

- Predictive Entropy Search
- Portfolios of adquisition functions
-...

**Comment by till-m** [comment]
Hey @oarcelus,

we're in the process of making acquisition functions easier to customize, see #447. The PR is currently on hold though, waiting for other changes. However the code is functional, so if you need this urgently, you should be able to install and create the functions you need based off of that branch. I hope this helps.

**Comment by bwheelz36** [comment]
closing as #447 is about to be merged.
