### ISSUE TITLE
cannot import acquisition

### ISSUE THREAD

**Issue by cnsolari** [bayesian-optimization/BayesianOptimization#517]
I tried to install using 
`pip install bayesian-optimization`

i can run basic optimization, but i have issues to using acquisition function. Any advice to help?

```
from bayes_opt import acquisition

ImportError: cannot import name 'acquisition' from 'bayes_opt' (c:\pyve\py39env\lib\site-packages\bayes_opt\__init__.py)
```
Here's what i have in '__init__.py', i dont see the same as you have in your git hub

```
__all__ = [
    "BayesianOptimization",
    "ConstraintModel",
    "UtilityFunction",
    "Events",
    "ScreenLogger",
    "JSONLogger",
    "SequentialDomainReductionTransformer",
]

```

**Comment by till-m** [comment]
Hi @cnsolari, see issue #500. Apologies for the inconvenience.
